service: aws-lambda-telegram-bot

plugins:
  - serverless-offline

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-southeast-1
  memorySize: 128
  timeout: 5
  endpointType: regional

  environment:
    TELEGRAM_BOT_TOKEN: ${file(./serverless.env.yml):TELEGRAM_BOT_TOKEN, ''}

functions:
  index:
    handler: handler.index
    events:
      - http:
          path: webhook
          method: post
          cors: true
  set-webhook:
    handler: handler.setWebhook
    events:
      - http:
          path: setWebhook
          method: post
          cors: true
